use TERADATA
SELECT COUNT(*) FROM 
[dbo].[DONATIONS] /* 3807374*/

SELECT COUNT(*) FROM 
[dbo].[DONATIONS_PARTICIPANTS] /*580089*/

SELECT COUNT(*) FROM 
[dbo].[DONATIONS_PARTICIPANTS_TEAMS] /* 480926 */

SELECT COUNT(*) FROM [dbo].[DONATIONS_PARTICIPANTS_TEAMS_EVENTS] /*480926 */